export const spec = {
  title: "De Morgan set transformation animation",
  shell: {
    width: 860,
  },
  svg: {
    width: 860,
    height: 680,
  },
  universe: {
    x: 130,
    y: 156,
    width: 600,
    height: 390,
    rx: 0,
    label: "U",
  },
  circles: {
    a: {
      cx: 380,
      cy: 348,
      r: 142,
      label: "A",
    },
    b: {
      cx: 480,
      cy: 348,
      r: 142,
      label: "B",
    },
    c: {
      cx: 654,
      cy: 548,
      r: 34,
      label: "C",
    },
  },
  labels: {
    universe: { x: 152, y: 184 },
    a: { x: 350, y: 236 },
    b: { x: 510, y: 236 },
    phase: { x: 430, y: 604 },
    equation: { x: 430, y: 92 },
    modeTabs: { y: 34 },
    mini: { x: 610, y: 556 },
  },
  modeTabs: [
    {
      key: "unionComplement",
      label: "(A ∪ B)ᶜ = Aᶜ ∩ Bᶜ",
      x: 166,
      width: 236,
    },
    {
      key: "intersectionComplement",
      label: "(A ∩ B)ᶜ = Aᶜ ∪ Bᶜ",
      x: 458,
      width: 236,
    },
  ],
  animation: {
    durationMs: 6000,
    loop: true,
  },
  states: {
    activeOpacity: 0.86,
    hoverOpacity: 0.28,
    mutedOpacity: 0.78,
    outlineActiveOpacity: 0.9,
    outlineMutedOpacity: 0.42,
    labelActiveOpacity: 1,
    labelMutedOpacity: 0.42,
  },
  regions: ["outside", "aOnly", "bOnly", "intersection"],
  modes: {
    unionComplement: {
      key: "unionComplement",
      title: "(A ∪ B)ᶜ",
      finalEquation: "(A ∪ B)ᶜ = Aᶜ ∩ Bᶜ",
      segments: [
        {
          startMs: 0,
          endMs: 1000,
          from: {},
          to: {},
          label: "(A ∪ B)ᶜ",
        },
        {
          startMs: 1000,
          endMs: 2000,
          from: {},
          to: { aOnly: 1, bOnly: 1, intersection: 1 },
          label: "A ∪ B",
        },
        {
          startMs: 2000,
          endMs: 3000,
          from: { aOnly: 1, bOnly: 1, intersection: 1 },
          to: { outside: 1 },
          label: "(A ∪ B)ᶜ",
          complement: true,
        },
        {
          startMs: 3000,
          endMs: 3750,
          from: { outside: 1 },
          to: { outside: 1, bOnly: 1 },
          label: "Aᶜ",
        },
        {
          startMs: 3750,
          endMs: 4500,
          from: { outside: 1, bOnly: 1 },
          to: { outside: 1 },
          label: "Aᶜ ∩ Bᶜ",
        },
        {
          startMs: 4500,
          endMs: 6000,
          from: { outside: 1 },
          to: { outside: 1 },
          label: "(A ∪ B)ᶜ = Aᶜ ∩ Bᶜ",
          final: true,
        },
      ],
      equationTokens: [
        { text: "(", role: "group" },
        { text: "A", hover: "a" },
        { text: " ∪ ", hover: "union" },
        { text: "B", hover: "b" },
        { text: ")ᶜ", hover: "lhsComplement" },
        { text: " = ", hover: "result" },
        { text: "Aᶜ", hover: "aComplement" },
        { text: " ∩ ", hover: "rhsOperator" },
        { text: "Bᶜ", hover: "bComplement" },
      ],
      hoverRegions: {
        a: { aOnly: 1, intersection: 1 },
        b: { bOnly: 1, intersection: 1 },
        union: { aOnly: 1, bOnly: 1, intersection: 1 },
        lhsComplement: { outside: 1 },
        result: { outside: 1 },
        aComplement: { outside: 1, bOnly: 1 },
        bComplement: { outside: 1, aOnly: 1 },
        rhsOperator: { outside: 1 },
      },
    },
    intersectionComplement: {
      key: "intersectionComplement",
      title: "(A ∩ B)ᶜ",
      finalEquation: "(A ∩ B)ᶜ = Aᶜ ∪ Bᶜ",
      segments: [
        {
          startMs: 0,
          endMs: 1000,
          from: {},
          to: {},
          label: "(A ∩ B)ᶜ",
        },
        {
          startMs: 1000,
          endMs: 2000,
          from: {},
          to: { intersection: 1 },
          label: "A ∩ B",
        },
        {
          startMs: 2000,
          endMs: 3000,
          from: { intersection: 1 },
          to: { outside: 1, aOnly: 1, bOnly: 1 },
          label: "(A ∩ B)ᶜ",
          complement: true,
        },
        {
          startMs: 3000,
          endMs: 3750,
          from: { outside: 1, aOnly: 1, bOnly: 1 },
          to: { outside: 1, bOnly: 1 },
          label: "Aᶜ",
        },
        {
          startMs: 3750,
          endMs: 4500,
          from: { outside: 1, bOnly: 1 },
          to: { outside: 1, aOnly: 1, bOnly: 1 },
          label: "Aᶜ ∪ Bᶜ",
        },
        {
          startMs: 4500,
          endMs: 6000,
          from: { outside: 1, aOnly: 1, bOnly: 1 },
          to: { outside: 1, aOnly: 1, bOnly: 1 },
          label: "(A ∩ B)ᶜ = Aᶜ ∪ Bᶜ",
          final: true,
        },
      ],
      equationTokens: [
        { text: "(", role: "group" },
        { text: "A", hover: "a" },
        { text: " ∩ ", hover: "intersection" },
        { text: "B", hover: "b" },
        { text: ")ᶜ", hover: "lhsComplement" },
        { text: " = ", hover: "result" },
        { text: "Aᶜ", hover: "aComplement" },
        { text: " ∪ ", hover: "rhsOperator" },
        { text: "Bᶜ", hover: "bComplement" },
      ],
      hoverRegions: {
        a: { aOnly: 1, intersection: 1 },
        b: { bOnly: 1, intersection: 1 },
        intersection: { intersection: 1 },
        lhsComplement: { outside: 1, aOnly: 1, bOnly: 1 },
        result: { outside: 1, aOnly: 1, bOnly: 1 },
        aComplement: { outside: 1, bOnly: 1 },
        bComplement: { outside: 1, aOnly: 1 },
        rhsOperator: { outside: 1, aOnly: 1, bOnly: 1 },
      },
    },
  },
  miniThreeSet: {
    label: "(A ∪ B ∪ C)ᶜ",
    x: 606,
    y: 480,
    width: 104,
    height: 86,
    circles: [
      { cx: 646, cy: 526, r: 26, label: "A" },
      { cx: 672, cy: 526, r: 26, label: "B" },
      { cx: 659, cy: 503, r: 26, label: "C" },
    ],
  },
};
